/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    AiCopilot: typeof import('./src/components/AiCopilot.vue')['default']
    AnalysisDashboard: typeof import('./src/components/AnalysisDashboard.vue')['default']
    ArticleEditor: typeof import('./src/components/ArticleEditor.vue')['default']
    Card: typeof import('primevue/card')['default']
    CompetitorAnalysis: typeof import('./src/components/tools/CompetitorAnalysis.vue')['default']
    ContentAuditor: typeof import('./src/components/tools/ContentAuditor.vue')['default']
    Copilotchat: typeof import('./src/components/tools/Copilotchat.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    SemanticAnalyzer: typeof import('./src/components/tools/SemanticAnalyzer.vue')['default']
    SeoBrief: typeof import('./src/components/SeoBrief.vue')['default']
    SeoForm: typeof import('./src/components/SeoForm.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
  }
}
